mkizka/tsukuriga

README.md
=> READMEのtypoを一箇所修正

core/templatetags/core_tags.py
=> fixes #4 current_siteの宣言スコープ修正

.gitignore, README.md, docker/Dockerfile, docker/createDocker.sh, docker/debugDocker.sh, docker/depend.sh
Dockerを用いたビルド手順について、スクリプトと共にREADMEに記載しました。
前回 #11 にて頂いた意見の「READMEにDockerでの手順を数行追記し、docker関連はdockerという名のディレクトリへ移管する」という方針に基づいた形です。
=> Added tool for build docker. And edit README.md

ajax/forms.py, ajax/models.py, ajax/views.py, core/templates/core/components/v-comment-item.html, core/views.py, upload/forms.py, upload/models.py
#12 について、ガイドラインの作成はまだですがモノだけ先に作っておきました
ご確認いただければ幸いです
=> 匿名コメント機能作成

README.md, docker/Dockerfile, docker/exec.sh
Dockerを使用する際のコマンドを簡略化しました
ご確認いただければ幸いです
=> Dockerを使用するスクリプトを修正

account/admin.py, account/forms.py, account/models.py, account/templates/users/components/direct-message-form.html, account/templates/users/profile.html, account/users/urls.py, account/users/views.py, ajax/models.py, browse/templates/browse/components/direct-message-item.html, browse/templates/browse/components/direct-message-list.html, core/utils.py, notify/templates/notify/components/types/directmessage.html
#26 の指摘に基づき、submitする形に書き換えました
commitログが複雑になること、書き込み先及び構造が大きく変わったことより、新規のブランチとして作成しました
また、作成時より状況が変わったので指摘以外には以下の2点の変更があります
1. video.htmlがvideo-item.htmlになったのに伴い、direct-message.htmlをdirect-message-item.htmlに変更しました
2. ajaxを使わない形となったため、匿名ユーザーを記した配列についてはcore.utilに移動しました
ご確認お願いします
=> 指摘に基づきDM機能を再作成

browse/context_processors.py, browse/models.py, templates/base/components/submenu.html, tsukuriga/settings/base.py
=> チャンネル一覧をサイドバーに表示

ajax/models.py, ajax/views.py, core/templates/core/components/v-comment-list/v-comment-item.html, notify/templates/notify/components/types/comment.html
#27 の準備をしていたのですが、フロント側から匿名コメントのusernameを取得できてしまうことに気づいたので修正しました
ご確認お願いします
=> 盗聴すれば匿名コメントの送信者を特定できる脆弱性を修正

ajax/models.py, ajax/views.py, assets/src/core/watch/comments.js, core/templates/core/components/v-comment-list/v-comment-item.html, notify/templates/notify/components/types/comment.html
#27 で用いるリプライボタンを作成しました
ユーザーへのリンク処理はまだ(というか~~masterから独立した~~#45 の派生プルリクとして送ろうと思います)ですが、これに則る場合「>>表示名@username 」となる文法をリンクに変換します(匿名コメントをリンクに変換する場合「>>表示名 」となります。ただ、リンク先を動画につけられたコメント一覧を参照するようになるまでは要らない話ですけども…)
ご確認お願いします
=> #27 リプライボタンを追加

ajax/models.py, assets/src/core/watch/comments.js, core/templates/core/components/v-comment-list/v-comment-item.html, core/templatetags/core_tags.py
#27 の一環としてユーザーに対する返信時のリンク処理を作成しました
ただし、core/templates/core/components/v-comment-list/v-comment-item.htmlについては#47 とconflictが起きるかもしれないのでご注意ください
=> ユーザーに対するリンク作成

assets/src/base/app.js, assets/src/core/thumbnail.js, assets/src/core/watch/comments.js, assets/src/core/watch/favorites.js, assets/src/core/watch/framebyframe.js, assets/src/core/watch/points.js, assets/src/utils.js
=> utils.jsのdoc関数をdocとdocAllに使い分ける

account/models.py, upload/decorators.py, upload/views.py
=> feat: 新規アカウント限定で10分以内の連続アップロードを制限

browse/models.py
#38 にて提示したPRの1です
大まかには以下のように実装しました
* Altwugの頃と同様の仕様
* Pointの日数対応
* 前回のcommitにおいて発生してたバグの修正
=> 人気順計算式(8割方テスト済み、エラーなし確認済み)

account/auth/decorators.py, account/auth/views.py, account/models.py
=> feat: アカウントの連続作成を制限

browse/models.py
#48 について、from_datetimeの返り値を修正し、それに合わせ各メソッドの処理も修正しました
ご確認お願いします
#38 にて使用したテストと同一のテストを実行済みです
=> fix:day_countが0未満の際のfrom_datetimeの返り値を2019年4月1日に修正

browse/models.py
#38 で話したとおりの、ランキング計算式の引き継ぎ漏れ部分、及び評価関数の修正をしました
ご確認お願いします
#64 とのコンフリクトが発生しないこと、実行時にエラーが起きないことまで確認済みです
=> fix:ランキング計算式の引き継ぎ漏れ部分修正

browse/templates/browse/components/video-list.html, core/templates/core/watch.html, core/views.py
=> feat: 関連動画の表示

ajax/models.py
#48 のリファクタについて、amendでは遡りきれなかったのでプルリクを作成し直しました
ご確認お願いします
=> fix: Pointモデルのusername_displayとjsonメソッド修正

web/tools/urls.py, web/tools/views.py, web/upload/models.py
=> feat: 集計データのcsv取得用URL追加

node/src/core/framebyframe.js, node/src/core/thumbnail.js, node/src/core/watch/framebyframe.js, web/core/templates/core/components/video-menu.html, web/core/templates/core/components/video-menu/framebyframe-input.html, web/core/templates/core/framebyframe.html, web/core/templates/core/thumbnail.html, web/core/urls.py, web/core/views.py
issue: #75 
ツイートに対応後、mp4への直リンクにも対応させてAltwugアーカイブページに使用する
ブランチ内容がだいぶ古いので1から作り直すことも検討
=> ツイートコマ送りツール

node/src/core/watch/framebyframe.js, node/src/utils.js, web/core/templates/core/framebyframe.html, web/tools/templates/altwug/index.html, web/tools/templates/archive/index.html, web/tools/urls.py, web/tools/views.py
=> Altwugアーカイブページ追加

docker-compose.yml, web/.dockerignore, web/Dockerfile
=> Dockerfile改善

web/notify/context_processors.py, web/notify/views.py, web/tsukuriga/settings/dev.py
=> 通知表示のN+1解消

node/src/base/scss/_video.scss, web/browse/templates/browse/components/video-item.html, web/core/management/commands/seed.py, web/core/views.py, web/upload/models.py
=> 投稿状態を分かりやすくする
